/**
 * Claude pre-pass that turns a brief user prompt into a structured video-frames
 * storyboard: a single "base scene" copy-pasted across every frame plus one
 * incremental `change` line per frame. The resulting JSON is persisted with the
 * frame set and used to build each Gemini frame prompt.
 */

import { generateText } from "./text-gen";
import {
  renderContextBlock,
  type GenerationContext,
} from "./generation-context";

export interface FrameStoryboard {
  /** Copy-pasted into every frame prompt. Full scene description. */
  base_scene: string;
  /** One entry per frame. Length === frameCount. */
  frames: { change: string }[];
  /** Optional one-line motion prompt for a downstream video model. */
  video_prompt?: string;
}

function buildSystemPrompt(
  ctx: GenerationContext,
  skillsContent: string | null,
  frameCount: number
): string {
  const parts: string[] = [
    "You are a video-frames storyboard planner. Given a brief user prompt and brand context, you produce a JSON storyboard for sequential keyframes that will be generated by an image model and stitched into a short video.",
    "",
    "Hard rules:",
    "- Output JSON ONLY. No prose, no markdown, no code fences.",
    '- The "base_scene" describes the full scene (setting, lighting direction, camera angle, props, atmosphere) and MUST stay valid for every frame.',
    '- Each frame\'s "change" is the ONE small incremental difference vs the previous frame. Camera, lighting, background stay identical unless they ARE the change.',
    `- Frame 1's change describes the starting state. Frame ${frameCount}'s change describes the completed state.`,
    "- Only 1-2 things should change between consecutive frames.",
    "- Respect any skills below — especially label-text preservation (every letter on the product must stay identical across all frames).",
    "",
    `JSON shape (exactly ${frameCount} frames):`,
    "{",
    '  "base_scene": "string",',
    `  "frames": [${Array.from({ length: frameCount }, () => '{"change": "string"}').join(", ")}],`,
    '  "video_prompt": "string (optional, one short line for the downstream video model)"',
    "}",
    "",
    renderContextBlock(ctx),
  ];

  if (skillsContent) {
    parts.push("---");
    parts.push(`[Skills]\n${skillsContent}`);
  }

  return parts.join("\n");
}

function stripFences(raw: string): string {
  let s = raw.trim();
  if (s.startsWith("```")) {
    // Strip opening fence (```json or ```)
    s = s.replace(/^```[a-zA-Z]*\n?/, "");
    // Strip closing fence
    s = s.replace(/\n?```\s*$/, "");
  }
  return s.trim();
}

function tryParse(raw: string, frameCount: number): FrameStoryboard {
  const cleaned = stripFences(raw);
  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    throw new Error(
      `invalid JSON: ${err instanceof Error ? err.message : "parse error"}`
    );
  }

  if (!parsed || typeof parsed !== "object") {
    throw new Error("root is not an object");
  }
  const obj = parsed as Record<string, unknown>;

  if (typeof obj.base_scene !== "string" || obj.base_scene.trim().length === 0) {
    throw new Error("base_scene must be a non-empty string");
  }
  if (!Array.isArray(obj.frames)) {
    throw new Error("frames must be an array");
  }
  if (obj.frames.length !== frameCount) {
    throw new Error(
      `frames must have exactly ${frameCount} entries, got ${obj.frames.length}`
    );
  }

  const frames: { change: string }[] = [];
  for (let i = 0; i < obj.frames.length; i++) {
    const f = obj.frames[i];
    if (!f || typeof f !== "object") {
      throw new Error(`frames[${i}] is not an object`);
    }
    const change = (f as Record<string, unknown>).change;
    if (typeof change !== "string" || change.trim().length === 0) {
      throw new Error(`frames[${i}].change must be a non-empty string`);
    }
    frames.push({ change });
  }

  const result: FrameStoryboard = {
    base_scene: obj.base_scene,
    frames,
  };

  if (typeof obj.video_prompt === "string" && obj.video_prompt.trim().length > 0) {
    result.video_prompt = obj.video_prompt;
  }

  return result;
}

/**
 * Generate a structured storyboard for a frame set. Retries once on parse
 * failure with a stricter reminder. Throws if the second attempt also fails —
 * the caller should surface a 500 and not create a frame set row.
 */
export async function generateFrameStoryboard(
  userPrompt: string,
  ctx: GenerationContext,
  skillsContent: string | null,
  frameCount: number
): Promise<FrameStoryboard> {
  const systemPrompt = buildSystemPrompt(ctx, skillsContent, frameCount);

  // First attempt
  let firstError: string | null = null;
  try {
    const raw = await generateText(systemPrompt, userPrompt);
    return tryParse(raw, frameCount);
  } catch (err) {
    firstError = err instanceof Error ? err.message : String(err);
    console.warn("[frame-storyboard] First attempt failed:", firstError);
  }

  // Retry with stricter reminder
  const retryUserPrompt = `${userPrompt}\n\nRETURN ONLY JSON. NO PROSE. NO CODE FENCES. NO MARKDOWN.`;
  try {
    const raw = await generateText(systemPrompt, retryUserPrompt);
    return tryParse(raw, frameCount);
  } catch (err) {
    const secondError = err instanceof Error ? err.message : String(err);
    throw new Error(
      `Storyboard generation failed after retry. First: ${firstError}. Second: ${secondError}`
    );
  }
}
