/**
 * Claude pre-pass that turns a brief user prompt into a structured video-frames
 * storyboard: a single "base scene" copy-pasted across every frame plus one
 * incremental `change` line per frame. The resulting JSON is persisted with the
 * frame set and used to build each Gemini frame prompt.
 */

import { generateText } from "./text-gen";
import {
  renderContextBlock,
  type GenContextProduct,
  type GenerationContext,
} from "./generation-context";

export interface FrameStoryboard {
  /** Copy-pasted into every frame prompt. Full scene description. */
  base_scene: string;
  /** One entry per frame. Length === frameCount. */
  frames: { change: string }[];
  /** Optional one-line motion prompt for a downstream video model. */
  video_prompt?: string;
}

function buildSystemPrompt(
  ctx: GenerationContext,
  skillsContent: string | null,
  frameCount: number
): string {
  const parts: string[] = [
    "You are a video-frames storyboard planner. Given a brief user prompt and brand context, you produce a JSON storyboard for sequential keyframes that will be generated by an image model and stitched into a short video.",
    "",
    "Hard rules:",
    "- Output JSON ONLY. No prose, no markdown, no code fences.",
    '- The "base_scene" describes the full scene (setting, lighting direction, camera angle, props, atmosphere) and MUST stay valid for every frame.',
    '- Each frame\'s "change" is the ONE small incremental difference vs the previous frame. Camera, lighting, background stay identical unless they ARE the change.',
    `- Frame 1's change describes the starting state. Frame ${frameCount}'s change describes the completed state.`,
    "- Only 1-2 things should change between consecutive frames.",
    "- Respect any skills below — especially label-text preservation (every letter on the product must stay identical across all frames).",
    "",
    "Product authority (HARD RULES — read carefully):",
    "- The [Generation Context] product list below is AUTHORITATIVE and EXCLUSIVE. Reference ONLY products that appear there, by their EXACT canonical names.",
    "- Do NOT invent additional products, variants, flavors, sizes, editions, colors, or sub-brands. Never follow a canonical product name with an extra capitalized word that isn't in the catalog. Example: if the catalog contains \"Foo\", writing \"Foo Deluxe\" or \"Foo Tropical\" is FORBIDDEN — that's inventing a variant.",
    "- The user prompt may mention variants, flavors, editions, sub-brands, colors, or sizes that are NOT in the catalog. You MUST silently IGNORE those mentions and use only the canonical catalog names. Treat the user as if they had said only the canonical name.",
    "- If the user asks for multiple distinct variants of the same product and only one exists in the catalog, use the one catalog product for all of them.",
    "- When describing a product in base_scene, use ONLY its canonical name. Do not add flavor/edition/variant modifiers unless those exact words appear in the product's `description` field in the context.",
    "- The product's visual appearance (label text, colors, branding, graphics) comes from the reference image the image model will see — NOT from your storyboard text. Do NOT describe the product's label, colors, or branding in detail. Describe only the product's position, action, and scale in the scene. The image model will replicate the product's appearance from the reference image.",
    "",
    "Physical scale (CRITICAL — most common failure mode):",
    "- The image model has no innate sense of how big a product is. You MUST anchor scale explicitly inside `base_scene` (not just inside per-frame changes).",
    "- `base_scene` MUST state, for each product in the scene: its real-world physical dimensions (e.g. height in cm, volume in ml/oz/g, or relative size like 'palm-sized', 'fits in one hand') AND name at least one co-visible scale-reference object that will be present in EVERY frame (a hand, a glass, a plate, a phone, a basket, a person's torso — whatever fits the scene).",
    "- The product's size relative to that scale reference must stay consistent across every frame. If `base_scene` says the product is half the height of the basket, every frame must respect that.",
    "- Frame 1 MUST contain the product visible AND already at correct scale next to its scale reference. Never start with the product invisible/off-screen/at extreme distance — the image model uses frame 1 as its anchor for every following frame, and an empty frame 1 leaves the model with no scale information to inherit.",
    "",
    "Camera motion sequences (push-in, pull-out, orbit):",
    "- Big distance changes across the sequence (e.g. 'far → extreme close-up') are the hardest case for scale consistency, because every frame re-frames the product. If the user asks for one, KEEP THE PRODUCT VISIBLE AND IN-SCALE FROM FRAME 1. The camera moves; the product's apparent size grows smoothly because the camera approached it, not because the product itself changed size.",
    "- Prefer small camera moves (10-20% closer per frame) over dramatic ones. If the user asks for a dramatic range, compress it: don't go from 'tiny silhouette' to 'extreme close-up' in 5 steps — start with the product already clearly visible and end with a moderate close-up.",
    "",
    `JSON shape (exactly ${frameCount} frames):`,
    "{",
    '  "base_scene": "string",',
    `  "frames": [${Array.from({ length: frameCount }, () => '{"change": "string"}').join(", ")}],`,
    '  "video_prompt": "string (optional, one short line for the downstream video model)"',
    "}",
    "",
    renderContextBlock(ctx),
  ];

  if (skillsContent) {
    parts.push("---");
    parts.push(`[Skills]\n${skillsContent}`);
  }

  return parts.join("\n");
}

function stripFences(raw: string): string {
  let s = raw.trim();
  if (s.startsWith("```")) {
    // Strip opening fence (```json or ```)
    s = s.replace(/^```[a-zA-Z]*\n?/, "");
    // Strip closing fence
    s = s.replace(/\n?```\s*$/, "");
  }
  return s.trim();
}

function tryParse(raw: string, frameCount: number): FrameStoryboard {
  const cleaned = stripFences(raw);
  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    throw new Error(
      `invalid JSON: ${err instanceof Error ? err.message : "parse error"}`
    );
  }

  if (!parsed || typeof parsed !== "object") {
    throw new Error("root is not an object");
  }
  const obj = parsed as Record<string, unknown>;

  if (typeof obj.base_scene !== "string" || obj.base_scene.trim().length === 0) {
    throw new Error("base_scene must be a non-empty string");
  }
  if (!Array.isArray(obj.frames)) {
    throw new Error("frames must be an array");
  }
  if (obj.frames.length !== frameCount) {
    throw new Error(
      `frames must have exactly ${frameCount} entries, got ${obj.frames.length}`
    );
  }

  const frames: { change: string }[] = [];
  for (let i = 0; i < obj.frames.length; i++) {
    const f = obj.frames[i];
    if (!f || typeof f !== "object") {
      throw new Error(`frames[${i}] is not an object`);
    }
    const change = (f as Record<string, unknown>).change;
    if (typeof change !== "string" || change.trim().length === 0) {
      throw new Error(`frames[${i}].change must be a non-empty string`);
    }
    frames.push({ change });
  }

  const result: FrameStoryboard = {
    base_scene: obj.base_scene,
    frames,
  };

  if (typeof obj.video_prompt === "string" && obj.video_prompt.trim().length > 0) {
    result.video_prompt = obj.video_prompt;
  }

  return result;
}

/**
 * Build a set of lowercased tokens that are "allowed" to appear after a
 * catalog product name — everything that shows up anywhere in the catalog
 * (names, descriptions, categories). Used by the catalog validator to decide
 * whether `{ProductName} {CapitalizedWord}` is a legitimate catalog phrase
 * or an invented variant.
 */
function buildAllowedVocab(products: GenContextProduct[]): Set<string> {
  const set = new Set<string>();
  const add = (s: string | null | undefined) => {
    if (!s) return;
    for (const w of s.split(/\s+/)) {
      const clean = w.replace(/[^\p{L}\p{N}']/gu, "").toLowerCase();
      if (clean) set.add(clean);
    }
  };
  for (const p of products) {
    add(p.name);
    add(p.description);
    add(p.category);
  }
  return set;
}

/**
 * Scan storyboard text for catalog violations: a canonical product name
 * followed by a capitalized word that is NOT in the catalog vocabulary. This
 * catches Claude inventing variants like "Aranxhata Exotic" when the catalog
 * only has "Aranxhata". Returns an empty array if everything is clean.
 */
export function validateStoryboardAgainstCatalog(
  sb: FrameStoryboard,
  products: GenContextProduct[]
): string[] {
  const violations: string[] = [];
  if (products.length === 0) return violations;

  const allowed = buildAllowedVocab(products);

  const texts: { where: string; text: string }[] = [
    { where: "base_scene", text: sb.base_scene },
    ...sb.frames.map((f, i) => ({
      where: `frames[${i}].change`,
      text: f.change,
    })),
  ];
  if (sb.video_prompt) {
    texts.push({ where: "video_prompt", text: sb.video_prompt });
  }

  for (const p of products) {
    const escaped = p.name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    // Match: product name followed by whitespace + a capitalized word
    // (uppercase letter + 1+ letters/apostrophe/hyphen).
    const re = new RegExp(`\\b${escaped}\\s+([A-Z][A-Za-z'’\\-]+)`, "g");
    for (const { where, text } of texts) {
      let m: RegExpExecArray | null;
      while ((m = re.exec(text)) !== null) {
        const word = m[1]!;
        if (!allowed.has(word.toLowerCase())) {
          violations.push(
            `${where}: "${p.name} ${word}" — "${word}" is not in the catalog for product "${p.name}". Use only the canonical name.`
          );
        }
      }
    }
  }
  return violations;
}

/**
 * Generate a structured storyboard for a frame set. Retries once on parse
 * failure OR catalog-violation failure, with a stricter reminder that
 * includes the specific failure reason. Throws if the second attempt also
 * fails — the caller should surface a 500 and not create a frame set row.
 */
export async function generateFrameStoryboard(
  userPrompt: string,
  ctx: GenerationContext,
  skillsContent: string | null,
  frameCount: number
): Promise<FrameStoryboard> {
  const systemPrompt = buildSystemPrompt(ctx, skillsContent, frameCount);

  const attempt = async (uPrompt: string): Promise<FrameStoryboard> => {
    const raw = await generateText(systemPrompt, uPrompt);
    const parsed = tryParse(raw, frameCount);
    const violations = validateStoryboardAgainstCatalog(parsed, ctx.products);
    if (violations.length > 0) {
      throw new Error(`catalog violations — ${violations.join(" | ")}`);
    }
    return parsed;
  };

  // First attempt
  let firstError: string | null = null;
  try {
    return await attempt(userPrompt);
  } catch (err) {
    firstError = err instanceof Error ? err.message : String(err);
    console.warn("[frame-storyboard] First attempt failed:", firstError);
  }

  // Retry with stricter reminder. Include the canonical product list and
  // the specific failure reason so Claude can self-correct.
  const canonicalList =
    ctx.products.length > 0
      ? ctx.products.map((p) => `"${p.name}"`).join(", ")
      : "(none — no products in catalog)";
  const retryUserPrompt = [
    userPrompt,
    "",
    "IMPORTANT — your previous attempt failed:",
    firstError,
    "",
    `The ONLY product names you may use are: ${canonicalList}. Do not write any variant, flavor, edition, or sub-brand extensions after these names. Do not invent new products.`,
    "Describe the product's position and action only — NOT its label, colors, or branding.",
    "RETURN ONLY JSON. NO PROSE. NO CODE FENCES. NO MARKDOWN.",
  ].join("\n");

  try {
    return await attempt(retryUserPrompt);
  } catch (err) {
    const secondError = err instanceof Error ? err.message : String(err);
    throw new Error(
      `Storyboard generation failed after retry. First: ${firstError}. Second: ${secondError}`
    );
  }
}
